<?php echo $this->tag->linkTo(["/user", "Log Out", 'class' => 'btn btn-success']); ?>
<div class="d-flex">
    <div>
        <h1>Load this page to add controllers</h1>

        <h3>Current Controllers - </h3>
        <?php
        if ($controllers)
            if ($controllers->count() > 0) {
                foreach ($controllers as $controller) { ?>
                <p>
                    <?php
                    echo $controller->controller;
                    ?>
                </p> <?php  };
                } ?>
    </div>


</div>