<h1>Add role</h1>

<?php echo $this->tag->form("/access/addrole?role=admin"); ?>

<p>
    <label for="roles">Add role</label>
    <?php echo $this->tag->textField("roles");
    echo $this->tag->submitButton(["Add", "class" => "btn btn-primary"]);
    echo $errorMsg;
    ?>
</p>
</form>

<h3>Current Roles - </h3>
<?php
if ($roles)
    if ($roles->count() > 0) {
        foreach ($roles as $role) { ?>
        <p>
            <?php
            echo $role->role;
            ?>
        </p> <?php  };
        } ?>