<h1 class="text-center">Give Permissions</h1>
<br>

<table class="table">
    <thead>Permissions</thead>
    <tr>
        <th>role</th>
        <th>controller</th>
        <th>Action</th>
    </tr><?php
            if ($permissions)
                if ($permissions->count() > 0) {
                    foreach ($permissions as $permission) { ?>
            <tr>
                <td><?php echo $permission->role ?></td>
                <td><?php echo $permission->controller ?></td>
                <td><?php echo $permission->action ?></td>
                <?php
                        if ($permission->role != "admin") {
                            echo " <td><a href='/access/del?role=admin&id=$permission->id'>Remove</a></td>";
                        }
                ?>

            </tr>

    <?php  };
                } ?>

</table>


<?php echo $this->tag->form("/access/buildacl?role=admin"); ?>
<select name='roles'>
    <?php if ($roles)
        if ($roles->count() > 0) {
            foreach ($roles as $role) {
                if ($role->role == "admin") {
                    continue;
                }
    ?>
            <option name='roles' value="<?php
                                        echo $role->role; ?>">
                <?php
                echo $role->role;
                ?>
            </option> <?php  };
                } ?>
</select>
<select name='controller'>
    <?php if ($controllers)
        if ($controllers->count() > 0) {

            foreach ($controllers as $controller) {
                if ($controller->controller == 'access') {
                    continue;
                };
    ?>
            <option name='controller' value="<?php
                                                echo $controller->controller; ?>">
                <?php
                echo $controller->controller;
                ?>
            </option> <?php  };
                } ?>

</select>

<select name='action'>


    <option value="index" name='action'>index</option>
    <option value="add" name='action'>add</option>
    <option value="update" name='action'>update</option>
    <option value="delete" name='action'>delete</option>
</select>
<?php echo $this->tag->submitButton(["Add Permission", "class" => "btn btn-primary"]); ?>
</form>