<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products</title>
</head>

<body>
    <?php
    echo $this->tag->linkTo(["/product/add", "Add Product", 'class' => 'btn btn-primary']);
    echo $this->tag->linkTo(["/order", "Orders", 'class' => 'btn btn-danger']);
    echo $this->tag->linkTo(["/settings", "Settings", 'class' => 'btn btn-secondary']);
    ?>
    <?php
    if ($products)
        if ($products->count() > 0) {
    ?>
        <table class="table table-bordered table-hover">
            <thead class="thead-light">
                <tr>
                    <th>product_ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Tags</th>
                    <th>Price</th>
                    <th>Stock</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="3">Total Products: <?php echo $products->count(); ?></td>
                </tr>
            </tfoot>
            <tbody>
                <?php


                foreach ($products as $product) { ?>
                    <tr>
                        <td><?php echo $product->product_id; ?></td>
                        <td><?php echo $product->name; ?></td>
                        <td><?php echo $product->description; ?></td>
                        <td><?php echo $product->tags; ?></td>
                        <td><?php echo $product->price; ?></td>
                        <td><?php echo $product->stock; ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>

    <?php
        }; ?>
</body>

</html>