<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order</title>
</head>

<body>
    <h2>Place Order</h2>

    <?php echo $this->tag->form(""); ?>

    <p>
        <label for="name">Customer Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="address">Customer Address</label>
        <?php echo $this->tag->textArea("address"); ?>
    </p>

    <p>
        <label for="zip">Zip Code</label>
        <?php echo $this->tag->textField("zip"); ?>
    </p>
    <select name="product">
        <?php
        if ($products)
            if ($products->count() > 0) {
                foreach ($products as $product) { ?>

                <option value='<?php echo $product->name; ?>' name='procuct'><?php echo $product->name; ?></option>
        <?php }
            }; ?>
    </select>
    <p>
        <label for="quantity">Quantity</label>
        <?php echo $this->tag->textField("quantity"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton(["Add", "class" => "btn btn-primary"]);
        echo $errorMessage;
        ?>
    </p>

    </form>
</body>

</html>