<?php
echo $this->tag->linkTo(["/order/addorder", "Add Order", 'class' => 'btn btn-primary']);
echo $this->tag->linkTo(["/product", "View Products", 'class' => 'btn btn-danger']);
echo $this->tag->linkTo(["/settings", "Settings", 'class' => 'btn btn-secondary']);

if ($orders)
    if ($orders->count() > 0) {
?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>order_ID</th>
                <th>Customer Name</th>
                <th>Address</th>
                <th>Zip Code</th>
                <th>Product</th>
                <th>Quantity</th>
            </tr>
        </thead>

        <tbody>
            <?php


            foreach ($orders as $order) { ?>
                <tr>
                    <td><?php echo $order->order_id; ?></td>
                    <td><?php echo $order->name; ?></td>
                    <td><?php echo $order->address; ?></td>
                    <td><?php echo $order->zip; ?></td>
                    <td><?php echo $order->product; ?></td>
                    <td><?php echo $order->quantity; ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

<?php
    }; ?>