<?php
echo $this->tag->linkTo(["/order/addo?role=" . $_GET['bearer'], "Add Order", 'class' => 'btn btn-primary']);
echo $this->tag->linkTo(["/product?role=" . $_GET['bearer'], "View Products", 'class' => 'btn btn-danger']);
echo $this->tag->linkTo(["/settings?role=" . $_GET['bearer'], "Settings", 'class' => 'btn btn-secondary']);
echo $this->tag->linkTo(["/user", "Log Out", 'class' => 'btn btn-success']);
if ($orders)
    if ($orders->count() > 0) {
?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>order_ID</th>
                <th>Customer Name</th>
                <th>Address</th>
                <th>Zip Code</th>
                <th>Product</th>
                <th>Quantity</th>
            </tr>
        </thead>

        <tbody>
            <?php


            foreach ($orders as $order) { ?>
                <tr>
                    <td><?php echo $order->order_id; ?></td>
                    <td><?php echo $order->name; ?></td>
                    <td><?php echo $order->address; ?></td>
                    <td><?php echo $order->zip; ?></td>
                    <td><?php echo $order->product; ?></td>
                    <td><?php echo $order->quantity; ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

<?php
    }; ?>